version: '3.8'

# WARN: Don't ever give any credentials in this file. This file is accessible to the end-user. I've done it because I'll only be using that for local development

services:
  db:
    image: postgres:15
    container_name: url_shortener_postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: localdbuser
      POSTGRES_PASSWORD: localPass123
      POSTGRES_DB: url_shortener_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
